## Changes needed for each project
# meta data for all bam, contain tumor-barcode, and its exome kit
# bamMeta: /data/coad_pass_bam.tsv
# samplesList: /data/TCGA_COAD_filtered_samples.yaml

# can be a subset of paires
# pairList: /data/TCGA_COAD_test_pairings.yaml

## path to tools ##
readCounterScript:  /mnt/data/hmmcopy_utils/bin/readCounter
ichorCNA_rscript:  /mnt/data/ichorCNA/scripts/runIchorCNA.R
ichorCNA_libdir: NULL
pyCountScript:  code/countPysam.py
TitanCNA_rscript: ../R_scripts/titanCNA.R
TitanCNA_selectSolutionRscript: ../R_scripts/selectSolution.R
TitanCNA_libdir:  ../../
TitanCNA_genomeStyle: UCSC

## path to reference files ##
ichorCNA_exons:
  "06 465 668 001": /mnt/data/input/gs/bucket1q2w/jpliu/titancna/tcga/liftovers/hglft_genome_3bc6_6b9910.filter.bed
  "5860504001": /mnt/data/input/gs/bucket1q2w/jpliu/titancna/tcga/liftovers/SeqCap_EZ_Exome_v2.hg38_filtered.bed
  "931070": /mnt/data/input/gs/austin_pipeline_mc3/titancna/liftovers/hglft38_genome_4d9d_2d6390.bed

ichorCNA_centromere:
  /mnt/data/input/gs/bucket1q2w/jpliu/titancna/tcga/refgrch38/GRCh38.GCA_000001405.2_centromere_acen.txt
refFasta:
  /mnt/data/input/gs/bucket1q2w/jpliu/titancna/tcga/refgrch38/Homo_sapiens_assembly38.fasta
snpDB:
  /mnt/data/input/gs/bucket1q2w/jpliu/titancna/tcga/refgrch38/hapmap_3.3.hg38.vcf
TitanCNA_centromere: /mnt/data/input/gs/bucket1q2w/jpliu/titancna/tcga/refgrch38/GRCh38.GCA_000001405.2_centromere_acen.txt 

## params for each step ##

## read depth params ##
chrs:
  chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrX,chrY
binSize:  10000

## ichorCNA params ##
ichorCNA_genomeStyle: UCSC
ichorCNA_gcWig: /mnt/data/input/gs/bucket1q2w/jpliu/titancna/tcga/refgrch38/gc_hg38_10kb.wig
ichorCNA_mapWig:  /mnt/data/input/gs/bucket1q2w/jpliu/titancna/tcga/refgrch38/map_hg38_10kb.wig
ichorCNA_chrs:  paste0('chr', c(1:22, \"X\"))
ichorCNA_chrTrain:  paste0('chr', c(1:22))
ichorCNA_normal:  c(0.5)  
ichorCNA_ploidy:  c(2,3)  
ichorCNA_estimateNormal:  TRUE
ichorCNA_estimatePloidy:  TRUE
ichorCNA_estimateClonality: TRUE
ichorCNA_scStates:  c(1,3)
ichorCNA_maxCN:  8
ichorCNA_includeHOMD: FALSE
ichorCNA_txnE:  0.9999
ichorCNA_txnStrength:  10000
ichorCNA_plotFileType:  png
ichorCNA_plotYlim:  c(-2,4)

## allele counts - samtools, pysam ##
#filterHETrscript: code/getPhasedHETSitesFromLLRVCF.R
map_quality:  10
base_quality: 10
vcf_quality:  100

## TitanCNA params ##
TitanCNA_numCores: 5
TitanCNA_maxNumClonalClusters: 5
TitanCNA_chrs:  paste0('chr', c(1:22, \"X\"))
TitanCNA_normalInit: 0.5
TitanCNA_maxPloidy: 3
TitanCNA_estimateNormal:  map
TitanCNA_estimatePloidy:  TRUE
TitanCNA_estimateClonality: TRUE
TitanCNA_alleleModel: binomial
TitanCNA_alphaK:  2500
TitanCNA_alphaKHigh: 2500
TitanCNA_alphaR:  2500
TitanCNA_txnExpLen: 1e15
TitanCNA_plotYlim:  c(-2,4)
TitanCNA_solutionThreshold: 0.05
# if hg38, need to have cytoband file
TitanCNA_cytobandFile: /mnt/data/input/gs/bucket1q2w/jpliu/titancna/tcga/refgrch38/cytoBand_hg38.txt
